exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
#paginate: 10
#pygments: true
safe: false
url: "http://localhost:4000"
excerpt_separator: "{{ more }}"
markdown_ext: markdown,mkd,mkdn,md
markdown: redcarpet
main_title: "Ciaran Andrews Architectural Consultant"
description: "Architectural Consultant"
title: "Ciaran Andrews Architectural Consultants"
