exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
#paginate: 10
#pygments: true
safe: false
#url: "http://localhost:4000"

# Serving

port: 4000
host: 0.0.0.0
baseurl: "" # does not include hostname

excerpt_separator: "{{ more }}"
markdown_ext: markdown,mkd,mkdn,md
markdown: kramdown
main_title: "Ciaran Andrews Architectural Consultant"
description: "Architectural Consultant"
title: "Ciaran Andrews Architectural Consultants"
